graph LR
    R1[#emsp;#emsp;#emsp;#emsp;#emsp;R1#emsp;#emsp;#emsp;#emsp;#emsp;] --- MidAdapter[Mid Adapter]
    R2[#emsp;#emsp;#emsp;#emsp;#emsp;R2#emsp;#emsp;#emsp;#emsp;#emsp;] --- MidAdapter
    EndAdapter[End Adapter] --- R2
    StartAdapter[Start Adapter] --- R1
